- name: configure pi
  hosts: all
  become: yes

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nmap
          - vim
          - bat
          - git
          - lsof
          - python3-pip
          - neofetch
          - avahi-utils

    - name: stop and disable bluetooth service
      ansible.builtin.systemd:
        name: bluetooth
        state: stopped
        enabled: false

    - name: stop and disable ModemManager service
      ansible.builtin.systemd:
        name: ModemManager
        state: stopped
        enabled: false

    - name: stop and disable wpa_supplicant service
      ansible.builtin.systemd:
        name: wpa_supplicant
        state: stopped
        enabled: false

    - name: check wifi radio status
      ansible.builtin.shell:
        cmd: nmcli radio wifi
      register: wifi_status
      changed_when: false

    - name: disable wifi radio if needed
      ansible.builtin.command:
        cmd: nmcli radio wifi off
      when: wifi_status.stdout | lower == "enabled"

    - name: check wwan radio status
      ansible.builtin.shell:
        cmd: nmcli radio wwan
      register: wwan_status
      changed_when: false

    - name: disable wwan radio if needed
      ansible.builtin.command:
        cmd: nmcli radio wwan off
      when: wwan_status.stdout | lower == "enabled"

    - name: remove ssh banner file
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/rename_user.conf
        state: absent
      notify: restart sshd

    - name: check for batcat binary
      ansible.builtin.stat:
        path: /usr/bin/batcat
      register: batcat_binary

    - name: create symbolic link for bat
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/bin/bat
        state: link
        force: yes
      when: batcat_binary.stat.exists

  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted