---
- name: configure pi
  hosts: all
  become: yes

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nmap
          - vim
          - bat
          - git

    - name: remove banner
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/rename_user.conf
        state: absent
      register: banner_file

    - name: restart sshd
      service:
        name: sshd
        state: restarted
      when: banner_file.changed

    - name: stat bat
      ansible.builtin.stat:
        path: /usr/bin/bat
      register: bat_stat

    - name: move batcat to bat
      command: mv /usr/bin/batcat /usr/bin/bat
      when: bat_stat.stat.exists == False

    - name: perform a full-upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes

    - name: check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: reboot the server if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes

    - name: clean up the apt cache
      ansible.builtin.apt:
        autoclean: yes
