---
- name: configure pi
  hosts: all
  become: yes

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nmap
          - vim
          - bat
          - git
          - lsof
          - python3-pip
          - neofetch
          - avahi-utils

    - name: stop bluetooth
      ansible.builtin.systemd:
        name: bluetooth
        state: stopped

    - name: disable bluetooth
      ansible.builtin.systemd:
        name: bluetooth
        enabled: false

    - name: stop modem crap
      ansible.builtin.systemd:
        name: ModemManager
        state: stopped

    - name: disable modem crap
      ansible.builtin.systemd:
        name: ModemManager
        enabled: false

    - name: stop wpa crap
      ansible.builtin.systemd:
        name: wpa_supplicant
        state: stopped

    - name: disable wpa crap
      ansible.builtin.systemd:
        name: wpa_supplicant
        enabled: false

    - name: check wifi radio status
      ansible.builtin.shell:
        cmd: nmcli radio wifi
      register: wifi_status

    - name: disable wifi radio if needed
      ansible.builtin.shell:
        cmd: nmcli radio wifi off
      when: wifi_status.stdout|lower == "enabled"

    - name: check wwan radio status
      ansible.builtin.shell:
        cmd: nmcli radio wwan
      register: wwan_status

    - name: disable wwan radio if needed
      ansible.builtin.shell:
        cmd: nmcli radio wwan off
      when: wwan_status.stdout|lower == "enabled"

    - name: remove banner
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/rename_user.conf
        state: absent
      register: banner_file

    - name: restart sshd
      service:
        name: sshd
        state: restarted
      when: banner_file.changed

    - name: stat bat
      ansible.builtin.stat:
        path: /usr/bin/bat
      register: bat_stat

    - name: move batcat to bat
      command: mv /usr/bin/batcat /usr/bin/bat
      when: bat_stat.stat.exists == False
