---
- name: configure pi
  hosts: all
  become: yes

  tasks:
    - name: install packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - nmap
          - vim
          - bat
          - git
          - aircrack-ng

    - name: stop avahi
      ansible.builtin.systemd:
        name: avahi-daemon
        state: stopped

    - name: disable avahi
      ansible.builtin.systemd:
        name: avahi-daemon
        enabled: false

    - name: stop bluetooth
      ansible.builtin.systemd:
        name: bluetooth
        state: stopped

    - name: disable bluetooth
      ansible.builtin.systemd:
        name: bluetooth
        enabled: false

    - name: remove banner
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/rename_user.conf
        state: absent
      register: banner_file

    - name: restart sshd
      service:
        name: sshd
        state: restarted
      when: banner_file.changed

    - name: stat bat
      ansible.builtin.stat:
        path: /usr/bin/bat
      register: bat_stat

    - name: move batcat to bat
      command: mv /usr/bin/batcat /usr/bin/bat
      when: bat_stat.stat.exists == False


